### ISSUE TITLE
Making use of mesh.rm_convertmodeto results in Python errors upon first mode switch of a new object.

### ISSUE THREAD

**Issue by jaston559** [roosterMAP/rmKit#3]
After rebinding my modes to the mesh.rm_convertmodeto commands that the addon supplies, I get a python error when trying to change selection mode from object mode to edit mode (vertex) or vertex to edge. This seems to only happen once for each new object once you try to swap modes. Only a minor inconvenience at the moment, as it seems the other tools that rely on mesh.rm_convertmodeto still work properly.

Python Error:

```
Python: Traceback (most recent call last):
  File "C:\Users\jaston\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\rmKit-main\addon\selectionmode.py", line 169, in execute
    for e in verts.edges:
  File "C:\Users\jaston\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\rmKit-main\rmlib\elem_set.py", line 555, in edges
    for e in v.link_edges:
ReferenceError: BMesh data of type BMVert has been removed
```

**Comment by roosterMAP** [comment]
Have you bound the ChangeModeTo commands located in the 3DView section of the rmKit prefs? I believe they both need to be bound for it to function correctly.

**Comment by roosterMAP** [comment]
This occurs because the outgoing edges driving the arc adjustment are parallel to oneanother. Ill add an exception to catch the error.
Could you maybe send a pic of the topology this is failing on? Id like to confirm that this isn't occurring on a valid input.

**Comment by jaston559** [comment]
It happens once for each object I create the first time you enter edit mode and try to switch modes within edit mode. Here's a cube that it happened to. I didn't make it through all the primitives that blender lets you create but it seems to happen on cubes, planes, spheres, cones, cylinders, and torus. 

Here are some exact repro steps as well. 

1. Start fresh Blender scene
2. Add a cube
3. With the cube selected go from object mode to edit mode
4. switch to a different editing mode ie vertex, edge or face
5. Error should appear


<img width="1010" alt="cube_example_01" src="https://github.com/roosterMAP/rmKit/assets/99584428/c27c3f18-66dc-4853-b526-cc2a125200c1">

Thanks for looking into this, and a huge thanks for all the great tools in this addon!

**Comment by roosterMAP** [comment]
Sorry for the confusing response. My last comment was meant for the other bug report.

I submitted a potential fix. Could you update and confirm? Also, have you bound both ChangeModeTo and ConvertModeTo? ChangeModeTo is in the View3D section of the rmKit Prefs and ConvertModeTo is in the Mesh section.

**Comment by jaston559** [comment]
Your changes seem to have fixed the python error. Thanks again!
