### ISSUE TITLE
Unbevel Tool behavior

### ISSUE THREAD

**Issue by RAFpz2015** [roosterMAP/rmKit#6]
![PsbSqRsP4s](https://github.com/roosterMAP/rmKit/assets/135660416/ec818739-8748-4c4f-9fde-b156b11872d1)
![Photoshop_ywoVzQ5ool](https://github.com/roosterMAP/rmKit/assets/135660416/ce92f4b0-c877-43ed-9b55-399d6e71cf8e)
Hey roosterMAP. I got an odd behavior with the unbevel tool. atm it works when selecting 2 connected edges from the loop or 2 edges apart from the same bevel loop. If I try to select all the edges that conform the bevel, the tool wont work. Meaning I need to do the unbevel operation multiple times to get the full unbevel result. This is with a with a 4 edge bevel. The MODO unbevel worked by selecting the 1st and last edge loop of the bevel and it would unbevel the whole thing with a single action. Curious if this is a bug.

**Comment by roosterMAP** [comment]
This is a regression. I submitted a fix.
