### ISSUE TITLE
Toggle Workplane & knife screen don't work in Blender 4.0.2

### ISSUE THREAD

**Issue by 1405100494** [roosterMAP/rmKit#8]
Toggle Workplane & knife screen & Connect Edges& others
don't work in Blender 4.0.2.
An error will cause the Blneder to crash immediately.

**Comment by raincity5** [comment]
Same issue here

**Comment by roosterMAP** [comment]
I submitted a bunch of fixes related to 4.0. These in particular are now fixed.
