### ISSUE TITLE
Transform and Orient Gui missingicons

### ISSUE THREAD

**Issue by RAFpz2015** [roosterMAP/rmKit#9]
![blender_XiNTidSxVd](https://github.com/roosterMAP/rmKit/assets/135660416/0201ec68-de7e-4ac3-860e-423adc470279)
When toggling between Local/Group/Anchor off, the icons in the Guis are missing. All other ones show when enabling Local/Group/Anchor. I thought the buttons were not working, they were just missing Icons.

**Comment by roosterMAP** [comment]
I cant repro on 3.6 and 4.0.2. Are there any errors in the consol? Could u send me the contents of ur consol log when this issue occures? Just go to Window->ToggleSystemConsole.
